# Generated by Django 4.2.2 on 2023-06-18 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='store',
        ),
    ]
